// prueba de commit
package views;
import views.administrar_inventario.AdminInvPage;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class InicioPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InicioPage.class.getName());

    /**
     * Creates new form Inicio
     */
    public InicioPage() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/gg.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmdVentas = new javax.swing.JButton();
        cmdCompras = new javax.swing.JButton();
        cmdProveedores = new javax.swing.JButton();
        cmdInventario = new javax.swing.JButton();
        cmdReportes = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Verduleria Glagerman");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panInicio.setBackground(new java.awt.Color(250, 250, 250));
        panInicio.setMaximumSize(new java.awt.Dimension(800, 600));
        panInicio.setMinimumSize(new java.awt.Dimension(800, 600));
        panInicio.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Negocio Glagerman");
        jLabel1.setAlignmentY(0.0F);

        cmdVentas.setBackground(new java.awt.Color(168, 197, 227));
        cmdVentas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdVentas.setText("Registrar Venta");
        cmdVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVentasActionPerformed(evt);
            }
        });

        cmdCompras.setBackground(new java.awt.Color(237, 237, 237));
        cmdCompras.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdCompras.setText("Registrar Compra");
        cmdCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdComprasActionPerformed(evt);
            }
        });

        cmdProveedores.setBackground(new java.awt.Color(237, 237, 237));
        cmdProveedores.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdProveedores.setText("Administrar Proveedor");
        cmdProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProveedoresActionPerformed(evt);
            }
        });

        cmdInventario.setBackground(new java.awt.Color(237, 237, 237));
        cmdInventario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdInventario.setText("Administrar Inventario");
        cmdInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdInventarioActionPerformed(evt);
            }
        });

        cmdReportes.setBackground(new java.awt.Color(237, 237, 237));
        cmdReportes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdReportes.setText("Reportes");
        cmdReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdReportesActionPerformed(evt);
            }
        });

        cmdSalir.setBackground(new java.awt.Color(244, 168, 168));
        cmdSalir.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panInicioLayout = new javax.swing.GroupLayout(panInicio);
        panInicio.setLayout(panInicioLayout);
        panInicioLayout.setHorizontalGroup(
            panInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInicioLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addGroup(panInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panInicioLayout.createSequentialGroup()
                        .addComponent(cmdSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panInicioLayout.createSequentialGroup()
                        .addGroup(panInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 294, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(280, 280, 280))
        );
        panInicioLayout.setVerticalGroup(
            panInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(cmdSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        System.exit(0); // Cerrar el sistema
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVentasActionPerformed
        VentasPage ventasPage = new VentasPage();
        ventasPage.setVisible(true);
        this.dispose(); // liberar recursos en vez de setVisible(false)
    }//GEN-LAST:event_cmdVentasActionPerformed

    private void cmdComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdComprasActionPerformed
        CompraAProveedoresPage comprasPage = new CompraAProveedoresPage();
        comprasPage.setVisible(true);       
        this.dispose(); // liberar recursos
    }//GEN-LAST:event_cmdComprasActionPerformed

    private void cmdProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProveedoresActionPerformed
        AdminProPage administrarPage = new AdminProPage();
        administrarPage.setVisible(true);   
        this.dispose(); // liberar recursos
    }//GEN-LAST:event_cmdProveedoresActionPerformed

    private void cmdInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdInventarioActionPerformed
        AdminInvPage administrarInvPage = new AdminInvPage();
        administrarInvPage.setVisible(true);   
        this.dispose(); // liberar recursos
    }//GEN-LAST:event_cmdInventarioActionPerformed

    private void cmdReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdReportesActionPerformed
        ReportesPage AdminReportesPage = new ReportesPage();
        AdminReportesPage.setVisible(true);   
        this.dispose(); // liberar recursos
    }//GEN-LAST:event_cmdReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> {
            Connection conex = posglagerman.ConexionDB.getConexionOrShowDialog();
            if (conex != null) {
                try {
                    conex.close();
                } catch (SQLException ex) {
                    logger.log(java.util.logging.Level.WARNING, "Error cerrando conexión de verificación al iniciar", ex);
                }
                // Mostrar mensaje de éxito UNA sola vez al inicio de la app.
                JOptionPane.showMessageDialog(null,
                    "Sistema abierto correctamente.",
                    "Conexión exitosa",
                    JOptionPane.INFORMATION_MESSAGE);
            }
            new InicioPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCompras;
    private javax.swing.JButton cmdInventario;
    private javax.swing.JButton cmdProveedores;
    private javax.swing.JButton cmdReportes;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JButton cmdVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panInicio;
    // End of variables declaration//GEN-END:variables
}
