package views;

import posglagerman.ConexionDB;
import javax.swing.JOptionPane;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ReportesPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportesPage.class.getName());

    /**
     * Creates new form ReportesPage
     */
    public ReportesPage() {
        initComponents();
        
        cargarTodo();  
    }
   
    private void cargarTodo() {
    String inicio = "0000-01-01";   // fecha mínima
    String fin = "9999-12-31";      // fecha máxima

    cargarCompras(inicio, fin);
    cargarVentas(inicio, fin);
}
    
    
    private void cargarCompras(String inicio, String fin) {

        DefaultTableModel model = (DefaultTableModel) tblCompras.getModel();
        model.setRowCount(0);

        String sql = "SELECT fecha_compra, total_compra, rut_proveedor FROM Compra "
                   + "WHERE fecha_compra BETWEEN ? AND ?";

        try (Connection conn = ConexionDB.getConexion();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, inicio);
            ps.setString(2, fin);

            ResultSet rs = ps.executeQuery();

            int totalGeneral = 0;

            while (rs.next()) {
                String fecha = rs.getString("fecha_compra");
                int total = rs.getInt("total_compra");
                String proveedor = rs.getString("rut_proveedor");

                model.addRow(new Object[]{fecha, proveedor, total});

                totalGeneral += total;
            }

            txtComprasT.setText(String.valueOf(totalGeneral));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error cargando compras: " + e.getMessage());
        }

    }
    
    private void cargarVentas(String inicio, String fin) {

        DefaultTableModel model = (DefaultTableModel) tblVentas.getModel();
        model.setRowCount(0);

        String sql = "SELECT fecha_venta, total_venta FROM Venta "
                   + "WHERE fecha_venta BETWEEN ? AND ?";

        try (Connection conn = ConexionDB.getConexion();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, inicio);
            ps.setString(2, fin);

            ResultSet rs = ps.executeQuery();

            int totalGeneral = 0;

            while (rs.next()) {
                String fecha = rs.getString("fecha_venta");
                int total = rs.getInt("total_venta");

                model.addRow(new Object[]{fecha, total});

                totalGeneral += total;
            }

            txtVentasT.setText(String.valueOf(totalGeneral));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error cargando ventas: " + e.getMessage());
        }

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFechaFin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        cmdBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmdVolverReportes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtComprasT = new javax.swing.JTextField();
        txtVentasT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFechaFin.setBackground(new java.awt.Color(237, 237, 237));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("REPORTES DE VENTAS Y COMPRAS");
        jLabel3.setToolTipText("");

        txtFechaInicio.setBackground(new java.awt.Color(237, 237, 237));

        cmdBuscar.setBackground(new java.awt.Color(211, 211, 211));
        cmdBuscar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdBuscar.setText("Buscar:");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Fecha Inicio:");

        cmdVolverReportes.setBackground(new java.awt.Color(244, 168, 168));
        cmdVolverReportes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdVolverReportes.setText("Volver");
        cmdVolverReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVolverReportesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Fecha fin:");

        tblCompras.setAutoCreateRowSorter(true);
        tblCompras.setBackground(new java.awt.Color(237, 237, 237));
        tblCompras.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Proveedor", "Total"
            }
        ));
        tblCompras.setFocusable(false);
        jScrollPane8.setViewportView(tblCompras);

        jTabbedPane1.addTab("Compras", jScrollPane8);

        tblVentas.setAutoCreateRowSorter(true);
        tblVentas.setBackground(new java.awt.Color(237, 237, 237));
        tblVentas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Total"
            }
        ));
        tblVentas.setFocusable(false);
        jScrollPane7.setViewportView(tblVentas);

        jTabbedPane1.addTab("Ventas", jScrollPane7);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Total Compras:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Total Ventas:");

        txtComprasT.setBackground(new java.awt.Color(237, 237, 237));
        txtComprasT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComprasTActionPerformed(evt);
            }
        });

        txtVentasT.setBackground(new java.awt.Color(237, 237, 237));
        txtVentasT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVentasTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(cmdBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtComprasT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVentasT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(cmdVolverReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtComprasT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVentasT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(cmdVolverReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        cargarVentas(txtFechaInicio.getText(), txtFechaFin.getText());
        cargarCompras(txtFechaInicio.getText(), txtFechaFin.getText());
    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void cmdVolverReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVolverReportesActionPerformed
        InicioPage inicioPage = new InicioPage();
        inicioPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdVolverReportesActionPerformed

    private void txtComprasTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComprasTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComprasTActionPerformed

    private void txtVentasTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVentasTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVentasTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportesPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdVolverReportes;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtComprasT;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtVentasT;
    // End of variables declaration//GEN-END:variables
}
