import java.sql.*; // Importar todo el sql 
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author seba
 */
public class InicioPage extends javax.swing.JFrame {
    String url="jdbc:sqlite:base_datos/negocioGlagerman.db";
    Connection conex;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InicioPage.class.getName());

    /**
     * Creates new form Inicio
     */
    public InicioPage() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        try{
            //Class.forName(url);
            conex = DriverManager.getConnection(url);
            
            if (conex != null){
                JOptionPane.showMessageDialog(null, "Conectado!!");
            }    
        } catch (Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmdVentas = new javax.swing.JButton();
        cmdCompras = new javax.swing.JButton();
        cmdProveedores = new javax.swing.JButton();
        cmdInventario = new javax.swing.JButton();
        cmdReportes = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panInicio.setBackground(new java.awt.Color(249, 250, 251));
        panInicio.setMaximumSize(new java.awt.Dimension(800, 600));
        panInicio.setMinimumSize(new java.awt.Dimension(800, 600));
        panInicio.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("POS Glagerman");
        jLabel1.setAlignmentY(0.0F);

        cmdVentas.setBackground(new java.awt.Color(168, 197, 227));
        cmdVentas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdVentas.setText("Registrar Venta");
        cmdVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVentasActionPerformed(evt);
            }
        });

        cmdCompras.setBackground(new java.awt.Color(211, 211, 211));
        cmdCompras.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdCompras.setText("Registrar Compra");
        cmdCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdComprasActionPerformed(evt);
            }
        });

        cmdProveedores.setBackground(new java.awt.Color(211, 211, 211));
        cmdProveedores.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdProveedores.setText("Administrar Proveedor");

        cmdInventario.setBackground(new java.awt.Color(211, 211, 211));
        cmdInventario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdInventario.setText("Administrar Inventario");

        cmdReportes.setBackground(new java.awt.Color(211, 211, 211));
        cmdReportes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdReportes.setText("Reportes");

        cmdSalir.setBackground(new java.awt.Color(244, 168, 168));
        cmdSalir.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panInicioLayout = new javax.swing.GroupLayout(panInicio);
        panInicio.setLayout(panInicioLayout);
        panInicioLayout.setHorizontalGroup(
            panInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInicioLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addGroup(panInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panInicioLayout.createSequentialGroup()
                        .addComponent(cmdSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panInicioLayout.createSequentialGroup()
                        .addGroup(panInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(cmdCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 294, Short.MAX_VALUE))))
        );
        panInicioLayout.setVerticalGroup(
            panInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(cmdSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        System.exit(0); // Cerrar el sistema
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVentasActionPerformed
        VentasPage ventasPage = new VentasPage();
        ventasPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cmdVentasActionPerformed

    private void cmdComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdComprasActionPerformed
        CompraAProveedoresPage comprasPage = new CompraAProveedoresPage();
        comprasPage.setVisible(true);       
        this.setVisible(false);
    }//GEN-LAST:event_cmdComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InicioPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCompras;
    private javax.swing.JButton cmdInventario;
    private javax.swing.JButton cmdProveedores;
    private javax.swing.JButton cmdReportes;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JButton cmdVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panInicio;
    // End of variables declaration//GEN-END:variables
}
